# Generated by Django 4.0.3 on 2022-03-30 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=50)),
                ('b_title', models.CharField(max_length=160)),
                ('b_author', models.CharField(max_length=50)),
                ('publish_date', models.DateField(default=datetime.date(2022, 3, 30))),
                ('total_quantity', models.BigIntegerField(max_length=5)),
                ('aval_quantity', models.BigIntegerField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
